#!/bin/sh
#
# $Id$
#
# $Log$
# Revision 1.2  1997/03/01 17:04:53  crook
# show usage of udebug parameter inot makesrc
#
# Revision 1.1  1997/01/13 09:41:28  crook
# Initial revision
#
#
# Targets are: all, pie, piedemon, ebsademon, ebsaboot, ebsaflash
# refer to eforth.mac for a description of each target
#
# NOTE: if you run on the PIE Card, don't try to use the cache stuff or
# the W@, W! instructions, because they won't work!!
#
# yes, I could have used make, but it didn't seem to give any advantage here.
#

default_target=ebsaflash

target=${1:-$default_target}



# build some images -nodebug to make them smaller? need KEEP in assembler source to make a difference


if [ $target = all ] || [ $target = pie ] ; then
  echo
  echo building pie.aif for PIE card, native I/O
  rm -f eforth.lst eforth.o
  gawk -f modsntx.awk eforth.mac
  gawk -v dict_pc=97248 -f makesrc.awk eforth.macs
  armasm -ARCH 4 eforth.macsw -PD 'TARGET SETS "PIE"'
  armlink -aif -bin -base 0x8000 -entry 0x8000 -debug -output pie.aif eforth.o
fi

if [ $target = all ] || [ $target = piedemon ] ; then
  echo
  echo building piedemn.aif for PIE card, I/O through DEMON
  rm -f eforth.lst eforth.o
  gawk -f modsntx.awk eforth.mac
  gawk -v dict_pc=97248 -f makesrc.awk eforth.macs
  armasm -ARCH 4 eforth.macsw -PD 'TARGET SETS "PIEDEMON"'
  armlink -aif -bin -base 0x8000 -entry 0x8000 -debug -output piedemn.aif eforth.o
fi

if [ $target = all ] || [ $target = ebsademon ] ; then
  echo
  echo building ebsademn.aif for EBSA-110, I/O through DEMON
  rm -f eforth.lst eforth.o
  gawk -f modsntx.awk eforth.mac
  gawk -v dict_pc=97248 -f makesrc.awk eforth.macs
  armasm -ARCH 4 eforth.macsw -PD 'TARGET SETS "EBSADEMON"'
  armlink -aif -bin -base 0x8000 -entry 0x8000 -debug -output ebsademn.aif eforth.o
fi

if [ $target = all ] || [ $target = ebsaboot ] ; then
  echo
  echo building ebsarom.bin for EBSA-110 boot EPROM
  rm -f eforth.lst eforth.o
  gawk -f modsntx.awk eforth.mac
  gawk -v dict_pc=1073806304 -f makesrc.awk eforth.macs
  armasm -ARCH 4 eforth.macsw -PD 'TARGET SETS "EBSABOOT"'
  armlink -bin -base 0x40000000 -entry 0x40000000 -output ebsarom.bin eforth.o
fi

if [ $target = all ] || [ $target = ebsaflash ] ; then
  echo
  echo building hfebfl.aif for EBSA-110, for programming into Flash
  rm -f hfsarom.lst hfsarom.o
  gawk -f modsntx.awk hfsarom.asm
#  gawk -v udebug=1 dict_pc=1073807360 -f makesrc.awk hfsarom.asms
  gawk -v dict_pc=1073807360 -f makesrc.awk hfsarom.asms
  armasm -ARCH 4 hfsarom.asmsw -list hf.lst -PD 'TARGET SETS "EBSA"' -PD 'MEMMAP SETS "DEMON"' -PD 'DEFIO SETS "COM2"' -PD 'DEFBAUD SETS "4"'
  armlink -aif -bin -base 0x400000c0 -entry 0x400000c0 -nodebug -output hfebfl.aif hfsarom.o
fi

exit 0





