#!/bin/sh
#
# $Id$
#
# $Log$
# Revision 1.5  1997/04/30 20:32:43  crook
# first working 21285 port
#
# Revision 1.3  1997/03/03 09:51:13  crook
# update for new build options in hfsarom.asm
#
# Revision 1.2  1997/03/01 17:04:53  crook
# show usage of udebug parameter inot makesrc
#
# Revision 1.1  1997/01/13 09:41:28  crook
# Initial revision
#
#
# Targets are: all, pie, piedemon, ebsa110demon, ebsa110boot, ebsa110flash
# refer to hfsarom.asm for a description of each target
#
# NOTE: if you run on the PIE Card, don't try to use the cache stuff or
# the W@, W! instructions, because they won't work!!
#
# yes, I could have used make, but it didn't seem to give any advantage here.
#

#default_target=ebsa110pbl
default_target=ebsa285pbl

target=${1:-$default_target}



# build some images -nodebug to make them smaller? need KEEP in assembler source to make a difference


if [ $target = all ] || [ $target = ebsa110demon ] ; then
  echo
  echo building hf110bl.aif for EBSA-110, for loading and starting via PBL
  rm -f hfsarom.lst hfsarom.o
  gawk -f modsntx.awk hfsarom.asm
  gawk -v dict_pc=1073807360 -f makesrc.awk hfsarom.asms
  armasm -ARCH 4 hfsarom.asmsw -list hf.lst -PD 'TARGET SETS "EBSA110"' -PD 'MEMMAP SETS "DEMON"' -PD 'DEFIO SETS "COMDSWI"' -PD 'DEFBAUD SETA 4'
  armlink -aif -bin -base 0x40000000 -entry 0x40000000 -nodebug -output hf110dm.aif hfsarom.o
fi

if [ $target = all ] || [ $target = ebsa110pbl ] ; then
  echo
  echo building hf110bl.aif for EBSA-110, for loading and starting via PBL
  rm -f hfsarom.lst hfsarom.o
  gawk -f modsntx.awk hfsarom.asm
#  gawk -v udebug=1 dict_pc=1073807360 -f makesrc.awk hfsarom.asms
  gawk -v dict_pc=1073807360 -f makesrc.awk hfsarom.asms
#  armasm -ARCH 4 hfsarom.asmsw -list hf.lst -PD 'TARGET SETS "EBSA110"' -PD 'MEMMAP SETS "DEMON"' -PD 'DEFIO SETS "COM2"' -PD 'DEFBAUD SETA 4'
  armasm -ARCH 4 hfsarom.asmsw -list hf.lst -PD 'TARGET SETS "EBSA110"' -PD 'MEMMAP SETS "PBLOADED"' -PD 'DEFIO SETS "COM2"' -PD 'DEFBAUD SETA 4'
  armlink -aif -bin -base 0x400000c0 -entry 0x400000c0 -nodebug -output hf110bl.aif hfsarom.o
fi

if [ $target = all ] || [ $target = ebsa285pbl ] ; then
  echo
  echo building hf285bl.aif for EBSA-285, for loading and starting via PBL
  rm -f hfsarom.lst hfsarom.o
  gawk -f modsntx.awk hfsarom.asm
#  gawk -v udebug=1 dict_pc=131072 -f makesrc.awk hfsarom.asms
  gawk -v dict_pc=131072 -f makesrc.awk hfsarom.asms
  armasm -ARCH 4 hfsarom.asmsw -list hf.lst -PD 'TARGET SETS "EBSA285"' -PD 'MEMMAP SETS "PBLOADED"' -PD 'DEFIO SETS "COM2"' -PD 'DEFBAUD SETA 4'
  armlink -aif -bin -base 0x000100c0 -entry 0x000100c0 -nodebug -output hf285bl.aif hfsarom.o
fi




if [ $target = release ]  ; then
  echo
  echo building set of release files in release
  rm -rf release/*
  co build modsntx.awk dat2tad.awk makesrc.awk
  cp build modsntx.awk dat2tad.awk makesrc.awk release

  co optional.f coreext.f multi.f muldemo.f double.f 110_hu.f 285_hu.f
  cp optional.f coreext.f multi.f muldemo.f double.f 110_hu.f 285_hu.f release

  co hfsarom.asm
  cp hfsarom.asm release

  ./build ebsa285pbl
  ./build ebsa110pbl
  ./build ebsa110demon
  cp hf285bl.aif hf110bl.aif hf110dm.aif release

  co readme.eng readme.kor readme.ks
  cp readme.eng readme.kor readme.ks release

  co whatsnew.eng whatsnew.kor whatsnew.ks
  cp whatsnew.eng whatsnew.kor whatsnew.ks release

  co hforth.html
  cp hforth.html release
  co readme.arm
  cp readme.arm release

  tar cf hf.tar release
  gzip hf.tar
  uuencode hf.tar.gz hf.tar.gz > hfarm.uu
fi

rm hfsarom.o hfsarom.asms hfsarom.asmsc hfsarom.asmsd hfsarom.asmst hfsarom.asmsw mucca.txt

exit 0





